### ISSUE TITLE
Review Inline tutorial

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/scala3-macro-tutorial#17]
https://github.com/lampepfl/scala3-macro-tutorial/blob/master/docs/inline.md

**Comment by b-studios** [comment]
I started revising the inline tutorial at #24

**Comment by b-studios** [comment]
The inline tutorial looks almost good to me now. The only thing that should be addressed IMO are the sections "Compiletime Operations" and "Macros". 

What is the underlying motivation for these two sections?

Depending on the answer to the above question, we might want to rephrase it as a "Where to go from here"-section. More compile time tools? -> "Compiletime Operations", more powerful implementations of `inline` methods? -> "Macros".

**Comment by b-studios** [comment]
I am happy to do the rephrasing, once the motivation is clear.
