### ISSUE TITLE
Publish as a web page

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/scala3-macro-tutorial#20]
Use the same template as [scala-3-migration-guide](https://scalacenter.github.io/scala-3-migration-guide).

See https://github.com/scalacenter/scala-3-migration-guide

**Comment by nicolasstucki** [comment]
@adpi2 how complex was that? What should we look at to make implement this?

**Comment by adpi2** [comment]
@mlachkar did all the work on this for the migration guide
see https://github.com/scalacenter/scala-3-migration-guide/commit/31638b76c32fb000a263f802e9d4c3802b08e412
and https://github.com/scalacenter/scala-3-migration-guide/commit/c6fc92e9ee6cbd051c17e56784d3da256f523731

For the style guide, it should not be as hard as copy pasting the css file

**Comment by adpi2** [comment]
We use the [mdoc](https://scalameta.org/mdoc/) plugin with [Docusaurus](https://docusaurus.io/)

**Comment by mlachkar** [comment]
So it quite simple. We use Docusaurus to create the website. 
There is the doc we followed https://scalameta.org/mdoc/docs/docusaurus.html that also points to Docusaurus doc. 
mdoc is not needed actually for docusaurus. 

I am happy to help if you have any issues adding Docusaurus.
